/**
 * GPU skinning. Bone matrices live in an RGBA32F texture, 4 texels per bone
 * (one per matrix column), uploaded by Skeleton.computeBoneTexture(). The
 * indexing below wraps on the texture width, so both the flat 4*n x 1 layout and
 * a squarer multi row layout work unchanged.
 * Include with '#include <skinning>'. Vertex shader only.
 *
 * The chunk owns the declaration of the skinning vertex attributes (locations 6
 * and 7). A shader that prefers to declare them itself must define
 * 'SKINNING_ATTRIBUTES_DECLARED' before the include.
 */
export const skinning: "\n#include <common>\n#ifndef SKINNING_GLSL_INCLUDED\n#define SKINNING_GLSL_INCLUDED\n\n#ifdef USE_SKINNING\n\n#ifndef SKINNING_ATTRIBUTES_DECLARED\n#define SKINNING_ATTRIBUTES_DECLARED\nlayout(location = 6) in vec4 aJoints;\nlayout(location = 7) in vec4 aWeights;\n#endif\n\n// Texture unit 6.\nuniform highp sampler2D uBoneTexture;\nuniform mat4 uBindMatrix;\nuniform mat4 uBindMatrixInverse;\n\n/** Read one bone matrix (column major, 4 consecutive texels). */\nmat4 getBoneMatrix(int boneIndex) {\n  int width = textureSize(uBoneTexture, 0).x;\n  int base = boneIndex * 4;\n\n  int i0 = base;\n  int i1 = base + 1;\n  int i2 = base + 2;\n  int i3 = base + 3;\n\n  int y0 = i0 / width;\n  int y1 = i1 / width;\n  int y2 = i2 / width;\n  int y3 = i3 / width;\n\n  vec4 c0 = texelFetch(uBoneTexture, ivec2(i0 - y0 * width, y0), 0);\n  vec4 c1 = texelFetch(uBoneTexture, ivec2(i1 - y1 * width, y1), 0);\n  vec4 c2 = texelFetch(uBoneTexture, ivec2(i2 - y2 * width, y2), 0);\n  vec4 c3 = texelFetch(uBoneTexture, ivec2(i3 - y3 * width, y3), 0);\n\n  return mat4(c0, c1, c2, c3);\n}\n\n/** Weighted blend of the four influencing bones, in bind space. */\nmat4 getSkinMatrix(vec4 joints, vec4 weights) {\n  float total = weights.x + weights.y + weights.z + weights.w;\n  vec4 w = total > 1e-5 ? weights / total : vec4(1.0, 0.0, 0.0, 0.0);\n  return w.x * getBoneMatrix(int(joints.x)) +\n         w.y * getBoneMatrix(int(joints.y)) +\n         w.z * getBoneMatrix(int(joints.z)) +\n         w.w * getBoneMatrix(int(joints.w));\n}\n\n/** Full skin matrix including the bind pose change of basis. */\nmat4 getSkinningMatrix() {\n  return uBindMatrixInverse * getSkinMatrix(aJoints, aWeights) * uBindMatrix;\n}\n\n/** Skin a position in object space. */\nvec3 skinPosition(vec3 position, mat4 skinMatrix) {\n  return (skinMatrix * vec4(position, 1.0)).xyz;\n}\n\n/** Skin a direction, ignoring translation. Non uniform bone scale is handled by\n *  the caller through the normal matrix, this keeps the vertex path cheap. */\nvec3 skinDirection(vec3 direction, mat4 skinMatrix) {\n  return mat3(skinMatrix) * direction;\n}\n\n/** Convenience: skin position, normal and tangent in one call. */\nvoid applySkinning(inout vec3 position, inout vec3 normal, inout vec3 tangent) {\n  mat4 skinMatrix = getSkinningMatrix();\n  position = skinPosition(position, skinMatrix);\n  mat3 skinRotation = mat3(skinMatrix);\n  normal = skinRotation * normal;\n  tangent = skinRotation * tangent;\n}\n\n#endif\n#endif\n";
